import React from 'react';
import { makeStyles, createStyles } from '@material-ui/core/styles';
import ButtonBase from '@material-ui/core/ButtonBase';
import Typography from '@material-ui/core/Typography';
import agriculture from '../assets/images/agriculture1.jpeg';
import logistics from '../assets/images/logistics1.jpeg';
import office from '../assets/images/office.jpeg';
import retail from '../assets/images/retail.jpeg';
import restaurant from '../assets/images/restaurant.jpeg';
import warehousing from '../assets/images/warehousing.jpeg';
import energy from '../assets/images/energy.jpeg';
import './DeviceView.css'

const images = [
  {
    url: agriculture,
    title: 'Agriculture',
    description: "Analyze your agricultural lands and find fruits, vegetables and other crops best fit for your land. Keep ahead by finding out all associated risks that you might come across in the future, and find remedies of overcome them. Make use of condition actions which will trigger alerts when your devices read unwanted values, values which could cause potential damage.",
    width: '100%',
  },
  {
    url: logistics,
    title: 'Logistics',
    description: "Keep a track of your trucks and other vehicles as your fragile goods are departed. Get the smoothest routes, monitor the status of your goods. Get an advance ultimatum of any potential damage to your goods coming your way. ",
    width: '100%',
  },
  {
    url: office,
    title: 'Smart Office',
    description: "Get an insight of the person waiting outside your home or you office. Manage the known faces as well as the unknown, add the unknowns to the list of knowns for the future. Recieve a notifiation of the person waiting outside.",
    width: '100%',
  },
  {
    url: retail,
    title: 'Retail',
    description: "Enhance the revenue generated by you business. Get an insight of the products benefitting the most as well as the products benefiting the least. Get recommendations to increase your revenues.",
    width: '100%',
  },
  {
    url: restaurant,
    title: 'Restaurant',
    description: "Keep a track of your frequent customers and their preferences, make use of our clustering algorithms to create deals for customers taking considertaion of both their preferences and making it economical for them. Thus benefitting both the customers and the restaurant revenue.",
    width: '100%',
  },
  {
    url: warehousing,
    title: 'Warehousing',
    description: 'Know what good come and go frequently and which ones remain in the warehouse for longer periods of time. Thus analyze the goods reaching their expiry dates before being departed and end up in loss of revenue. Know which goods or products are more beneficial to kept in greater quantities and vice versa.',
    width: '100%',
  },
  {
    url: energy,
    title: 'Energy',
    description: 'Estimate the peak hours, reduce the electricity cost and make efficient use of electricity.',
    width: '100%',
  },
];

const useStyles = makeStyles((theme) =>
  createStyles({
    root: {
      display: 'flex',
      flexWrap: 'wrap',
      minWidth: 300,
      width: '100%',
    },
    image: {
      position: 'relative',
      height: 325,
      margin:10,
      [theme.breakpoints.down('xs')]: {
        width: '100% !important', // Overrides inline-style
        height: 100,
      },
      '&:hover, &$focusVisible': {
        zIndex: 1,
        '& $imageBackdrop': {
          opacity: 0.15,
        },
        '& $imageMarked': {
          opacity: 0,
        },
        '& $imageTitle': {
          border: '4px solid currentColor',
        },
      },
    },
    focusVisible: {},
    imageButton: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 50,
      bottom: 0,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      color: theme.palette.common.white,
    },
    imageDescription:{
      position: 'relative',
      top: 80,
      left: 0,
      color: theme.palette.common.white,
      right: 0,
      padding:100,

    },
    imageSrc: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      backgroundSize: 'cover',
      backgroundPosition: 'center 40%',
    },
    imageBackdrop: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      backgroundColor: theme.palette.common.black,
      opacity: 0.4,
      transition: theme.transitions.create('opacity'),
    },
    imageTitle: {
      position: 'absolute',
      padding: `${theme.spacing(2)}px ${theme.spacing(4)}px ${theme.spacing(1) + 6}px`,
    },
    imageMarked: {
      height: 3,
      width: 18,
      backgroundColor: theme.palette.common.white,
      position: 'absolute',
      bottom: -2,
      left: 'calc(50% - 9px)',
      transition: theme.transitions.create('opacity'),
    },
  }),
);

export default function UseCases() {
  const classes = useStyles();

  return (
    <div className='DevicesMain' >
            
    <h1 style={{color:'purple'}}>Let's Begin</h1>
    <div className='devicesContainer'>
    <div className={classes.root}>
      {images.map((image) => (
        <ButtonBase
          focusRipple
          key={image.title}
          className={classes.image}
          focusVisibleClassName={classes.focusVisible}
          style={{
            width: image.width,
            justifyContent:"space-between",
          }}
        >
          <span
            className={classes.imageSrc}
            style={{
              backgroundImage: `url(${image.url})`,
            }}
          />
          
          <span className={classes.imageBackdrop} />
          <span className={classes.imageDescription}/>
          <span className={classes.imageButton}>
           
            <Typography
              component="span"
              variant="subtitle1"
              color="inherit"
              className={classes.imageTitle}
            >
              {image.title}
             
              <span className={classes.imageMarked} />
            </Typography>
            <Typography
            className={classes.imageDescription}
            component="span"
              variant="subtitle1"
              color="inherit"
              
            >
              {image.description}
             
            </Typography>
            
          </span>
         
        </ButtonBase>
        
        
      ))}
    </div>
    </div>
    </div>
  );
}